name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Bun
        # Installs Bun, making 'bun install' and 'bun run' available
        uses: oven-sh/setup-bun@v1

      - name: Install Node Dependencies (Bun)
        # Using bun install with --frozen-lockfile for a clean, consistent CI install
        run: bun install --frozen-lockfile

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        # Building frontend assets using Bun
        run: bun run build

      - name: Tests
        run: ./vendor/bin/pest
